### PR TITLE
arrays of objects of  some specific shapes

### PR DESCRIPTION
**Pull request by susaneshy**
i created an array with objects inside the array and then created a method to calculate the area of each object shape, this prints the area of each object in the array.

### CODE REVIEW

**Comment by andela-oadesanya** [comment]
Your code works well but you did not indent properly. Work on the indentation of all your code including the areaofshapes and resend pull request.

**Comment by susaneshy** [comment]
Thank you sir. I just re-indented all the codes as instructed sir.

**Comment by andela-oadesanya** [comment]
Well done. Good job.

**Comment by susaneshy** [comment]
Thank you sir.

On 13 September 2015 at 13:09, Oluwatosin Adesanya <notifications@github.com

**Pull request merged**
